from .response import SearchResponse, SearchResult, SearchType, ResultsBySource
from .contents import (
    ContentsResponse,
    ContentsResult,
    ContentsResultSuccess,
    ContentsResultFailed,
    ContentsJobCreateResponse,
    ContentsJobStatus,
    ExtractEffort,
    ContentsResponseLength,
)
from .datasources import (
    Datasource,
    DatasourcePricing,
    DatasourceCoverage,
    DatasourcesResponse,
    DatasourceCategory,
    DatasourceCategoriesResponse,
    DatasourceCategoryType,
)
from .answer import (
    AnswerResponse,
    AnswerSuccessResponse,
    AnswerErrorResponse,
    AnswerRequest,
    SearchMetadata,
    AIUsage,
    CostBreakdown,
    ExtractionMetadata,
    SUPPORTED_COUNTRY_CODES,
)
from .deepresearch import (
    AlertEmailConfig,
    DeepResearchMode,
    DeepResearchStatus,
    FileAttachment,
    MCPServerConfig,
    Deliverable,
    DeliverableResult,
    SearchConfig,
    Progress,
    ChartDataPoint,
    ChartDataSeries,
    ImageMetadata,
    DeepResearchSource,
    Usage,
    DeepResearchCreateResponse,
    DeepResearchStatusResponse,
    DeepResearchTaskListItem,
    DeepResearchListResponse,
    DeepResearchUpdateResponse,
    DeepResearchCancelResponse,
    DeepResearchDeleteResponse,
    DeepResearchTogglePublicResponse,
)

# Source format types
from typing import Literal, Union

SourceFormat = Union[str]  # Can be domain, URL, or dataset format
ValidatedSource = str  # A source that has passed validation

__all__ = [
    "SearchResponse",
    "SearchResult",
    "SearchType",
    "ResultsBySource",
    "ContentsResponse",
    "ContentsResult",
    "ContentsResultSuccess",
    "ContentsResultFailed",
    "ContentsJobCreateResponse",
    "ContentsJobStatus",
    "ExtractEffort",
    "ContentsResponseLength",
    "Datasource",
    "DatasourcePricing",
    "DatasourceCoverage",
    "DatasourcesResponse",
    "DatasourceCategory",
    "DatasourceCategoriesResponse",
    "DatasourceCategoryType",
    "AnswerResponse",
    "AnswerSuccessResponse",
    "AnswerErrorResponse",
    "AnswerRequest",
    "SearchMetadata",
    "AIUsage",
    "CostBreakdown",
    "ExtractionMetadata",
    "SUPPORTED_COUNTRY_CODES",
    "SourceFormat",
    "ValidatedSource",
    "AlertEmailConfig",
    "DeepResearchMode",
    "DeepResearchStatus",
    "FileAttachment",
    "MCPServerConfig",
    "Deliverable",
    "DeliverableResult",
    "SearchConfig",
    "Progress",
    "ChartDataPoint",
    "ChartDataSeries",
    "ImageMetadata",
    "DeepResearchSource",
    "Usage",
    "DeepResearchCreateResponse",
    "DeepResearchStatusResponse",
    "DeepResearchTaskListItem",
    "DeepResearchListResponse",
    "DeepResearchUpdateResponse",
    "DeepResearchCancelResponse",
    "DeepResearchDeleteResponse",
    "DeepResearchTogglePublicResponse",
]
